baseURL: https://ligato.io/
languageCode: en-us
title: Ligato
theme: hugo-fresh

params:
  navbarlogo:
    # Logo (from /images/logos/___)
    image: logos/new-logo-ligato-dark.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Ligato
    # Hero subtitle (optional)
    subtitle: An Open Source Go Framework for Building Applications to Control and Manage Cloud Native Network Functions (CNF)
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://docs.ligato.io/"
    # Hero image (from /images/___)
    image: ligato/ligato3.svg
    # Footer logos (from /images/logos/clients/___.svg)
    # Metz: replace client logos with FD.io, CNCF, K8S, Contiv VPP
    clientlogos:
    - grey-fdio
    - kubernetes-seeklogo.com
    - Go-Logo
    - contiv-icon
    - etcd
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Documentation
    url: "https://docs.ligato.io/"
  - title: Github
    sublinks:
    - title: Infra
      url: "https://github.com/ligato/cn-infra"
    - title: VPP Agent
      url: "https://github.com/ligato/vpp-agent"
    - title: All Repositories
      url: "https://github.com/ligato"
  - title: Videos
    sublinks:
      - title: Fosdem 2019 "VPP & Ligato use cases" talk
        url: https://fosdem.org/2019/schedule/event/vpp_ligato_as_ipsec_gateway/
      - title: Contiv VPP User Interface
        url: https://youtu.be/GKaJkskZAnQ
      - title: FD.io in a Cloud Native World, Ed Warnicke, Cisco Systems
        url: https://www.youtube.com/watch?v=SdLwSb0JSAs
  - title: Blog
    sublinks:
      - title: CNFs with a Dose of Ligato and FD.io/VPP
        url: "/blog/cnf-ligato-fdio"
  section1:
    title: Learn more about Ligato
    subtitle: All About CNFs, Ligato and Use Cases
    tiles:
    - title: What is a CNF?
      icon: mouse-globe
      text: Virtual Network Functions in Containers
      url: "cnf/cnf-def"
      buttonText: Learn More
    - title: Ligato Framework
      icon: plug-cloud
      text: Agents/Plugins for CNF Control & Management
      url: "architecture/lig-framework-overview"
      buttonText: Learn More
    - title: Use Cases
      icon: laptop-cloud
      text: Solutions Using the Ligato VPP Agent
      url: "use-cases/ligato-use-cases"
      buttonText: Learn More
  section2:
    title: Leveraging Open Source Technologies
    subtitle: Rapid Innovation Development and Deployment
    features:
    - title: Key Value Datastores
      text: Efficient storage and distribution of network configurations
      # Icon (from /images/illustrations/icons/___.svg)
      icon: etcd-blue
    - title: Written in Golang
      text: Programming language of choice for peformance and concurrency
      icon: golang
    - title: API Protocols for Process and Apps Communications
      text: Plugins including gRPC for building and running APIs
      icon: grpc
  section3:
    title: One Framework
    subtitle: Build CNFs for Existing and Future Networks
    image: ligato/ligato-front-pillar-grey-bg2.svg
    buttonText: Get started
    buttonLink: "https://docs.ligato.io/en/latest/user-guide/quickstart/"
  footer:
    # Logo (from /images/logos/___)
    logo: ligato-diamond.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/ligato
      icon: github
    - link: https://hub.docker.com/u/ligato
      icon: docker
    - link: https://twitter.com/ligatoProject
      icon: twitter
    - link: https://ligato.slack.com/
      icon: slack
    bulmalogo: false
    quicklinks:
#      column1:
#        title: "Golang"
#        links:
#        - text: Golang.org
#          link: https://golang.org
#        - text: Go by Example
#          link: https://gobyexample.com/
#        - text: Hello World in Go
#          link: https://gobyexample.com/hello-world
#        - text: Our roadmap
#          link: /
#        - text: Request features
#          link: /
      column2:
        title: "Documentation"
        links:
        - text: Quickstart
          link: "https://docs.ligato.io/en/latest/user-guide/quickstart/"
        - text: Concepts
          link: "https://docs.ligato.io/en/latest/user-guide/concepts/"
        - text: Hello World
          link: "https://docs.ligato.io/en/latest/tutorials/01_hello-world/"
        - text: FAQ
          link: "https://docs.ligato.io/en/latest/user-guide/faq/"
disableKinds: ["taxonomy", "taxonomyTerm", "section"]
